// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Q_WKUNoEWX0bb4vlfWfJtgsatB2-ZsU',
    appId: '1:671149348322:web:1779396cc002e00414d5bb',
    messagingSenderId: '671149348322',
    projectId: 'instagram-flutter-clone-8db8f',
    authDomain: 'instagram-flutter-clone-8db8f.firebaseapp.com',
    storageBucket: 'instagram-flutter-clone-8db8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6_YCFvCuL3R_QXeknSp94HV3b_8_QnGs',
    appId: '1:671149348322:android:3c8341352aab42de14d5bb',
    messagingSenderId: '671149348322',
    projectId: 'instagram-flutter-clone-8db8f',
    storageBucket: 'instagram-flutter-clone-8db8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7OHZ3XWpQhS8h61iMKtZNHB_JTGyI4E',
    appId: '1:671149348322:ios:80809cf114beb2aa14d5bb',
    messagingSenderId: '671149348322',
    projectId: 'instagram-flutter-clone-8db8f',
    storageBucket: 'instagram-flutter-clone-8db8f.appspot.com',
    iosClientId: '671149348322-cahj7aibfub06c3q5q4e2sj988m0do35.apps.googleusercontent.com',
    iosBundleId: 'com.instagramflutter.app',
  );
}
